export const pay = [{
    title: '核心源码',
    subtitle: 'avue的核心源码',
    vip: 2,
    nowmoney: '266.66',
    money: '299.99',
    list: [{
        title: 'avue核心源码解读',
        bold: true
    }, {
        title: '大量的可配置组件源码解读',
        bold: true
    }, {
        title: '更多vue的骚技巧的玩法',
        bold: true
    }, {
        title: '无任何协议限制,可二次开发',
        bold: true
    }, {
        title: '专属的开发者文档，助你快速掌握'
    }, {
        title: '支持IE8+等系列浏览器'
    }, {
        title: '学习开发基于vue第三方组件的学习'
    }, {
        title: '私人交流学习群'
    }, {
        title: '前端最新干货分享'
    }, {
        title: '免费的私人git私服'
    }]
}, {
    title: '模版源码',
    subtitle: 'avue-cli的核心源码',
    vip: 2,
    nowmoney: '266.66',
    money: '299.99',
    list: [{
        title: '面向全屏幕尺寸的响应式适配能力',
        bold: true
    }, {
        title: '支持IE8+等系列浏览器',
        bold: true
    }, {
        title: '全新的前端错误日志监控机制',
        bold: true
    }, {
        title: '基于最新的avue2.x底层开发',
        bold: true
    }, {
        title: '前端路由动态服务端加载',
        bold: true
    }, {
        title: '专属的开发者文档，助你快速掌握',
    }, {
        title: '灵活的多款主题自由配置'
    }, {
        title: '模块的可拆卸化,达到开箱即用'
    }, {
        title: '免费的私人git私服'
    }, {
        title: '解放重复crud和form的枯燥劳动'
    }, {
        title: '私人交流学习群'
    }, {
        title: '前端最新干货分享'
    }]
}, {
    title: '全家桶',
    subtitle: 'avue系列的全部源码',
    v: true,
    vip: 1,
    nowmoney: '366.66',
    money: '399.99',
    list: [{
        title: '可完全用于商用',
        bold: true,
    }, {
        title: '后期升级全部免费',
        bold: true,
    }, {
        title: '同时拥有“核心源码”和“模版源码”的授权',
        bold: true,
    }, {
        title: '获得avue中全部的vip特权',
        bold: true
    }, {
        title: '可附赠avue系列全家桶源码学习',
        bold: true
    }, {
        title: '包含avue2.x和avue-cli2.x源码'
    }, {
        title: '包含avue-form表单拖拽工具源码'
    }, {
        title: '包含avue-pig最新avue-cli对接pigx和pig'
    }, {
        title: '包含avue-cli2html版本的的源码'
    }, {
        title: '包含avue-house一个房屋采集系统案例'
    }, {
        title: '包含avue-api接口管理工具源码'
    }]
}]


export const extend = [{
    title: '富文本编辑框',
    tags: 'ueditor',
    author: 'smallwei',
    info: '基于vue-quill-editor插件的第三方的富文本编辑框',
    git: 'https://gitee.com/smallweigit/avue-plugin-ueditor',
    npm: 'https://www.npmjs.com/package/avue-plugin-ueditor',
    demo: 'ueditor'
}, {
    title: '地图插件',
    tags: 'map',
    author: 'smallwei',
    info: '基于高德地图插件坐标选取插件',
    git: 'https://gitee.com/smallweigit/avue-plugin-map',
    npm: 'https://www.npmjs.com/package/avue-plugin-map',
    demo: 'maps'
}, {
    title: '穿梭框',
    tags: 'transfer',
    author: 'smallwei',
    info: '基于element-ui中的transfer插件的穿梭框',
    git: 'https://gitee.com/smallweigit/avue-plugin-transfer',
    npm: 'https://www.npmjs.com/package/avue-plugin-transfer',
    demo: 'transfer',
}, {
    title: '下拉树',
    tags: 'treeselect',
    author: 'liyuchuan',
    info: '基于@riophae/ vue-treeselect封装的下拉树形选择',
    git: 'https://gitee.com/yuchuanli/avue-plugin-tresselect.git',
    npm: 'https://www.npmjs.com/package/avue-plugin-treeselect'
}, {
    title: '表格查询框',
    tags: 'dynamicquery',
    author: 'liyuchuan',
    info: '基于elementui 表格封装的弹出表格选择',
    git: 'https://gitee.com/yuchuanli/avue-plugin-dynamicquery.git',
    npm: 'https://www.npmjs.com/package/avue-plugin-dynamicquery',
    demo: 'dynamicquery'
}]

export const list = [{
    title: '支持各种主流浏览器',
    first: true,
    second: true,
}, {
    title: '第三方登录（微信，QQ）',
    first: true,
    second: true,
}, {
    title: '炫彩主题（换色，换肤）',
    first: true,
    second: true,
}, {
    title: '短信登录',
    first: true,
    second: true,
}, {
    title: '菜单搜索',
    first: true,
    second: true,
}, {
    title: '标签导航',
    first: true,
    second: true,
}, {
    title: '错误日志监控',
    first: true,
    second: true,
}, {
    title: '动态加载图标',
    first: true,
    second: true,
}, {
    title: '锁屏功能',
    first: true,
    second: true,
}, {
    title: 'iframe支持',
    first: true,
    second: true,
}, {
    title: '路由权限',
    first: true,
    second: true,
}, {
    title: '菜单权限',
    first: true,
    second: true,
}, {
    title: '页面缓冲',
    first: false,
    second: true,
}, {
    title: '服务端动态路由',
    first: false,
    second: true,
}, {
    title: '高级嵌套路由',
    first: false,
    second: true,
}, {
    title: '无限级菜单',
    first: false,
    second: true,
}, {
    title: '多终端适配',
    first: false,
    second: true,
}, {
    title: 'IE9+支持',
    first: false,
    second: true,
}, {
    title: '源码讲解文档',
    first: false,
    second: true,
}, {
    title: 'Avue核心源码',
    first: false,
    second: true,
}, {
    title: '新功能优先体验',
    first: false,
    second: true,
}, {
    title: '技术支持',
    first: false,
    second: true,
}, {
    title: 'git私服',
    first: false,
    second: true,
}, {
    title: '加入内部吹B群',
    first: false,
    second: true,
}]