export default [{
    title: '核心源码',
    subtitle: 'avue的核心源码',
    vip: 2,
    nowmoney: '149.9',
    money: '299.9',
    list: [{
        title: 'avue核心源码解读',
        bold: true
    }, {
        title: '大量的可配置组件源码解读',
        bold: true
    }, {
        title: '更多vue的骚技巧的玩法',
        bold: true
    }, {
        title: '无任何协议限制,可二次开发',
        bold: true
    }, {
        title: '专属的开发者文档，助你快速掌握'
    }, {
        title: '支持IE9+等系列浏览器'
    }, {
        title: '学习开发基于vue第三方组件的学习'
    }, {
        title: '私人交流学习群'
    }, {
        title: '前端最新干货分享'
    }, {
        title: '免费的私人git私服'
    }]
}, {
    title: '模版源码',
    subtitle: 'avue-cli的核心源码',
    vip: 2,
    nowmoney: '149.9',
    money: '299.9',
    list: [{
        title: '面向全屏幕尺寸的响应式适配能力',
        bold: true
    }, {
        title: '支持IE9+等系列浏览器',
        bold: true
    }, {
        title: '全新的前端错误日志监控机制',
        bold: true
    }, {
        title: '基于最新的avue2.x底层开发',
        bold: true
    }, {
        title: '前端路由动态服务端加载',
        bold: true
    }, {
        title: '专属的开发者文档，助你快速掌握',
    }, {
        title: '灵活的多款主题自由配置'
    }, {
        title: '模块的可拆卸化,达到开箱即用'
    }, {
        title: '免费的私人git私服'
    }, {
        title: '解放重复crud和form的枯燥劳动'
    }, {
        title: '私人交流学习群'
    }, {
        title: '前端最新干货分享'
    }]
}, {
    title: '全家桶',
    subtitle: 'avue系列的全部源码',
    v: true,
    vip: 1,
    nowmoney: '199.9',
    money: '399.9',
    list: [{
        title: '同时拥有“核心源码”和“模版源码”的授权',
        bold: true,
    }, {
        title: '获得avue中全部的vip特权',
        bold: true
    }, {
        title: '可附赠avue系列全家桶源码学习',
        bold: true
    }, {
        title: '包含avue2.x和avue-cli2.x源码'
    }, {
        title: '包含avue-form表单拖拽工具源码'
    }, {
        title: '包含avue-pig最新avue-cli对接pigx和pig'
    }, {
        title: '包含avue-cli2html版本的的源码'
    }, {
        title: '包含avue-house一个房屋采集系统案例'
    }, {
        title: '包含avue-api接口管理工具源码'
    }, {
        title: '可远程协助解决问题'
    }]
}]