export const pay = [{
    title: '后台模版',
    subtitle: 'avue-cli的快速开发后台模版',
    vip: 2,
    nowmoney: '99.99',
    list: [{
        title: '面向全屏幕尺寸的响应式适配能力',
        bold: true
    }, {
        title: '支持IE9+等系列浏览器',
        bold: true
    }, {
        title: '全新的前端错误日志监控机制',
        bold: true
    }, {
        title: '基于最新的avue底层开发',
        bold: true
    }, {
        title: '前端路由动态服务端加载',
        bold: true
    }, {
        title: '灵活的多款主题自由配置'
    }, {
        title: '专属的开发者文档，助你快速掌握',
    }, {
        title: '模块的可拆卸化,达到开箱即用'
    }, {
        title: '免费的私人git私服'
    }, {
        title: '解放重复crud和form的枯燥劳动'
    }, {
        title: '私人交流学习群'
    }, {
        title: '前端最新干货分享'
    }]
}, {
    title: 'Avuex',
    subtitle: 'avuex的核心源码',
    vip: 1,
    nowmoney: '999.99',
    list: [{
        title: '一键集成表格的导出excel，打印，等常用功能',
        bold: true,
    }, {
        title: '底层代码可重用轻松对接多个UI框架，不止局限element-ui',
        bold: true,
    }, {
        title: '底层更加完善的开发错误调试机制，轻量级的自动构建脚手架上手更容易',
        bold: true
    }, {
        title: '一套代码多个终端自适应',
        bold: true,
    }, {
        title: '一键集成表格的导出excel，打印，等常用功能',
        bold: true,
    }, {
        title: '表格的批量操作,表单的级联操作更加便捷'
    }, {
        title: '新增大量常用组件（搜索，选项卡）'
    }, {
        title: '新增大量全新可配置的骚属性'
    }, {
        title: '丰富的数据展示模版组件包'
    }, {
        title: '手机版的avue，写法与pc端一致'
    }, {
        title: '专属的开发者文档，助你快速掌握',
    }]
}, {
    title: '全家桶',
    subtitle: 'avue系列的全部源码',
    v: true,
    vip: 1,
    nowmoney: '499.99',
    list: [{
        title: '赠送专属自己的官网网站代码（avuex官网）',
        bold: true,
    }, {
        title: '可购买后可用于商业化开发，永久更新授权使用',
        bold: true,
    }, {
        title: '后期更新和新产品将全部免费',
        bold: true,
    }, {
        title: '拥有avue系列项目的全部代码',
        bold: true,
    }, {
        title: '提供远程技术支持和问题解答',
        bold: true,
    }]
}]


export const extend = [{
    title: '富文本编辑框',
    tags: 'ueditor',
    author: 'smallwei',
    info: '基于vue-quill-editor插件的第三方的富文本编辑框',
    git: 'https://gitee.com/smallweigit/avue-plugin-ueditor',
    npm: 'https://www.npmjs.com/package/avue-plugin-ueditor',
    demo: 'ueditor'
}, {
    title: '地图插件',
    tags: 'map',
    author: 'smallwei',
    info: '基于高德地图插件坐标选取插件',
    git: 'https://gitee.com/smallweigit/avue-plugin-map',
    npm: 'https://www.npmjs.com/package/avue-plugin-map',
    demo: 'maps'
}, {
    title: '穿梭框',
    tags: 'transfer',
    author: 'smallwei',
    info: '基于element-ui中的transfer插件的穿梭框',
    git: 'https://gitee.com/smallweigit/avue-plugin-transfer',
    npm: 'https://www.npmjs.com/package/avue-plugin-transfer',
    demo: 'transfer',
}, {
    title: '下拉树',
    tags: 'treeselect',
    author: 'liyuchuan',
    info: '基于@riophae/ vue-treeselect封装的下拉树形选择',
    git: 'https://gitee.com/yuchuanli/avue-plugin-tresselect.git',
    npm: 'https://www.npmjs.com/package/avue-plugin-treeselect'
}, {
    title: '表格查询框',
    tags: 'dynamicquery',
    author: 'liyuchuan',
    info: '基于elementui 表格封装的弹出表格选择',
    git: 'https://gitee.com/yuchuanli/avue-plugin-dynamicquery.git',
    npm: 'https://www.npmjs.com/package/avue-plugin-dynamicquery',
    demo: 'dynamicquery'
}]

export const list = [{
    title: '支持各种主流浏览器',
    first: true,
    second: true,
}, {
    title: '第三方登录（微信，QQ）',
    first: true,
    second: true,
}, {
    title: '炫彩主题（换色，换肤）',
    first: true,
    second: true,
}, {
    title: '短信登录',
    first: true,
    second: true,
}, {
    title: '菜单搜索',
    first: true,
    second: true,
}, {
    title: '标签导航',
    first: true,
    second: true,
}, {
    title: '错误日志监控',
    first: true,
    second: true,
}, {
    title: '动态加载图标',
    first: true,
    second: true,
}, {
    title: '锁屏功能',
    first: true,
    second: true,
}, {
    title: 'iframe支持',
    first: true,
    second: true,
}, {
    title: '路由权限',
    first: true,
    second: true,
}, {
    title: '菜单权限',
    first: true,
    second: true,
}, {
    title: '页面缓冲',
    first: false,
    second: true,
}, {
    title: '服务端动态路由',
    first: false,
    second: true,
}, {
    title: '高级嵌套路由',
    first: false,
    second: true,
}, {
    title: '无限级菜单',
    first: false,
    second: true,
}, {
    title: '多终端适配',
    first: false,
    second: true,
}, {
    title: 'IE9+支持',
    first: false,
    second: true,
}, {
    title: '源码讲解文档',
    first: false,
    second: true,
}, {
    title: 'Avue核心源码',
    first: false,
    second: true,
}, {
    title: '新功能优先体验',
    first: false,
    second: true,
}, {
    title: '技术支持',
    first: false,
    second: true,
}, {
    title: 'git私服',
    first: false,
    second: true,
}, {
    title: '加入内部吹B群',
    first: false,
    second: true,
}]