import EchartBar from 'packages/echart/bar';
import EchartPie from 'packages/echart/pie';
import EchartLine from 'packages/echart/line';
import EchartTable from 'packages/echart/table';
import EchartFlop from 'packages/echart/Flop';
import EchartDatetime from 'packages/echart/datetime';
import EchartText from 'packages/echart/text';
import EchartSwiper from 'packages/echart/swiper';
import EchartIframe from 'packages/echart/iframe';
import EchartVideo from 'packages/echart/video';
import EchartWordCloud from 'packages/echart/wordcloud';
import EchartGauge from 'packages/echart/gauge';
import EchartProgress from 'packages/echart/progress';
import EchartMaps from 'packages/echart/map';
import EchartImg from 'packages/echart/img';
import EchartImgBorder from 'packages/echart/imgborder';
import EchartTabs from 'packages/echart/tabs';
import EchartSlide from 'packages/echart/slide';
import EchartPictorialBar from 'packages/echart/pictorialbar';
import EchartRadar from 'packages/echart/radar';
import EchartFunnel from 'packages/echart/funnel';
import EchartScatter from 'packages/echart/scatter';
import EchartCommon from 'packages/echart/common';
import EchartDatav from 'packages/echart/datav';

export default { EchartRadar, EchartScatter, EchartFunnel, EchartSlide, EchartTabs, EchartVideo, EchartWordCloud, EchartPictorialBar, EchartMaps, EchartImg, EchartImgBorder, EchartBar, EchartGauge, EchartIframe, EchartSwiper, EchartTable, EchartPie, EchartText, EchartLine, EchartFlop, EchartDatetime, EchartProgress, EchartCommon, EchartDatav };
