import Bar from 'packages/echart/bar';
import Pie from 'packages/echart/pie';
import Line from 'packages/echart/line';
import Table from 'packages/echart/table';
import Flop from 'packages/echart/Flop';
import Datetime from 'packages/echart/Datetime';
import Text from 'packages/echart/Text';
import Swiper from 'packages/echart/swiper';
import Iframe from 'packages/echart/iframe';
import Video from 'packages/echart/video';
import WordCloud from 'packages/echart/wordCloud';
import Gauge from 'packages/echart/gauge';
import Progress from 'packages/echart/progress';
import Maps from 'packages/echart/map';
import Img from 'packages/echart/img';
import ImgBorder from 'packages/echart/imgBorder';
import Tabs from 'packages/echart/tabs';
import Slide from 'packages/echart/slide';
import PictorialBar from 'packages/echart/pictorialBar';
import Radar from 'packages/echart/radar';
import Funnel from 'packages/echart/funnel';
import Scatter from 'packages/echart/scatter';

export default [Radar, Scatter, Funnel, Slide, Tabs, Video, WordCloud, PictorialBar, Maps, Img, ImgBorder, Bar, Gauge, Iframe, Swiper, Table, Pie, Text, Line, Flop, Datetime, Progress];
