//crud配置文件
export default {
    //标题
    editTitle: '编 辑',
    addTitle: '新 增',
    viewTitle: '查 看',
    menuTitle: '操作',
    tipStartTitle: '当前表格已选择',
    tipEndTitle: '项',
    //尺寸
    menuWidth: 240,
    //文字
    viewBtnTitle: '查 看',
    editBtnTitle: '编 辑',
    addBtnTitle: '新 增',
    delBtnTitle: '删 除',
    updateBtnTitle: '修 改',
    saveBtnTitle: '新 增',
    cancelBtnTitle: '取 消',
    columnBtnTitle: '多 选',
    searchBtnTitle: '搜 索',
    emptyBtnTitle: '清 空',
    tipBtnTitle: '清空',
    menuBtnTitle: '功 能',
    cellEditBtnTitle: '修改',
    cellSaveBtnTitle: '保存',
    //图标
    viewBtnIcon: 'el-icon-view',
    editBtnIcon: 'el-icon-edit',
    addBtnIcon: 'el-icon-plus',
    delBtnIcon: 'el-icon-delete',
    searchBtnIcon: 'el-icon-search',
    emptyBtnIcon: 'el-icon-delete',
    cellEditBtnIcon: 'el-icon-edit',
    cellSaveBtnIcon: 'el-icon-check',
    columnBtnIcon: 'el-icon-menu',
    refreshBtnIcon: 'el-icon-refresh',
    searchboxBtnIcon: 'el-icon-search',
    //显隐
    viewBtn: false,
    editBtn: true,
    addBtn: true,
    delBtn: true,
    cellBtn: false,
    dateBtn: false,
    refreshBtn: true,
    columnBtn: true,
    searchBtn: true,
    menuBtn: false,
    selectClearBtn: true,
    searchShow: true,
    tip: true,
    dialogWidth: '50%',
    formFullscreen: false,
    customClass: '',
    pageBackground: true,
    page: true,
    menu: true,
    indexLabel: '#',
    filterMultiple: true,
    calcHeight: 300,
    title: '表格标题',
    width: '100%',
    dateDefault: false,
    //搜索参数
    searchMultiple: ['checkbox', 'tree', 'select']
}